[variables]
# NODE_VERSION = "18" # Supprimé car nous utilisons Deno
DENO_CONFIG = "/app/deno.json" # Indique à Deno d'utiliser ce fichier de configuration avec un chemin absolu

[providers.deno]
enabled = true
config_file = "/app/deno.json"   # Chemin absolu pour le fichier de configuration Deno
# entrypoint a été supprimé pour minimiser l'intervention du provider
no_install = true                # Demande à Nixpacks de ne pas exécuter sa routine d'installation Deno par défaut

[providers.node]
enabled = false

[phases.setup]
# Nixpacks devrait installer Deno automatiquement si le fournisseur est activé.
# Si des paquets Nix spécifiques à Deno sont nécessaires, ils peuvent être ajoutés ici.
# nixPkgs = ["deno"] # Exemple, peut ne pas être nécessaire

[phases.install]
# Commande explicite pour mettre en cache les dépendances en partant du point d'entrée principal.
# Nixpacks ne devrait plus exécuter sa propre logique de cache Deno grâce à no_install = true.
cmds = ["deno cache --config /app/deno.json src/main.tsx"]

[phases.build]
# Pour Deno, la mise en cache est souvent la principale étape de "build".
# Si d'autres étapes de build sont nécessaires, ajoutez-les ici.
cmds = [] # Laissez vide si seul le cache est nécessaire

[phases.start]
# Commande de démarrage explicite car entrypoint a été retiré de la configuration du provider Deno.
cmd = "deno run --allow-net --allow-read --allow-env --config /app/deno.json src/main.tsx"