-- Import data for table: subscription_plans
-- Generated from backup_insert.sql

INSERT INTO public.subscription_plans (id, name, description, price_cents, duration_days, features, is_active, sort_order, created_at) VALUES ('1', 'Découverte', 'Essai gratuit', '0', '30', '["Accès limité", "1 bon par mois"]', 'f', '1', '2025-12-19 03:01:45.176844+00');
INSERT INTO public.subscription_plans (id, name, description, price_cents, duration_days, features, is_active, sort_order, created_at) VALUES ('2', 'Classique', 'Accès complet', '999', '30', '["Accès complet", "5 bons par mois"]', 'f', '2', '2025-12-19 03:01:45.176844+00');
INSERT INTO public.subscription_plans (id, name, description, price_cents, duration_days, features, is_active, sort_order, created_at) VALUES ('3', 'Premium', 'Accès illimité', '2499', '90', '["Accès illimité", "Bons illimités", "Offres exclusives"]', 'f', '3', '2025-12-19 03:01:45.176844+00');
INSERT INTO public.subscription_plans (id, name, description, price_cents, duration_days, features, is_active, sort_order, created_at) VALUES ('4', 'Annuel', 'Meilleur prix', '7999', '365', '["Tout inclus", "2 mois offerts"]', 'f', '4', '2025-12-19 03:01:45.176844+00');
INSERT INTO public.subscription_plans (id, name, description, price_cents, duration_days, features, is_active, sort_order, created_at) VALUES ('5', 'Gratuit', 'Pour découvrir nos activités', '0', '365', '{"features": ["Accès à toutes les activités (tarif de base)", "Newsletter mensuelle", "Compte personnel"], "discount_percent": 0}', 't', '1', '2025-12-21 01:16:33.497597+00');
INSERT INTO public.subscription_plans (id, name, description, price_cents, duration_days, features, is_active, sort_order, created_at) VALUES ('6', 'Passionné', 'Pour les amateurs d''activités nautiques', '1500', '365', '{"features": ["15% de réduction sur toutes les activités", "Accès prioritaire aux réservations", "Événements VIP", "Support prioritaire"], "discount_percent": 15}', 't', '2', '2025-12-21 01:16:34.08432+00');
INSERT INTO public.subscription_plans (id, name, description, price_cents, duration_days, features, is_active, sort_order, created_at) VALUES ('7', 'Expert', 'L''expérience ultime', '9000', '365', '{"features": ["25% de réduction sur toutes les activités", "Accès illimité aux équipements", "Événements exclusifs", "Service conciergerie dédié", "Assurance activités incluse"], "discount_percent": 25}', 't', '3', '2025-12-21 01:16:34.651701+00');
