#!/usr/bin/env node
/**
 * Script de Mise à Jour Configuration Supabase
 * ============================================
 * Met à jour automatiquement la configuration Supabase dans l'application
 * pour pointer vers une nouvelle instance (cloud vers auto-hébergé ou vice-versa)
 */

import fs from 'fs';
import path from 'path';

interface SupabaseConfig {
  url: string;
  key: string;
  description?: string;
}

interface UpdateOptions {
  target: SupabaseConfig;
  createBackup: boolean;
  backupDir: string;
  validateConfig: boolean;
}

class SupabaseConfigUpdater {
  private configFilePath: string;
  private options: UpdateOptions;
  private timestamp: string;

  constructor(options: UpdateOptions) {
    this.options = options;
    this.configFilePath = path.join(process.cwd(), 'src/integrations/supabase/client.ts');
    this.timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  }

  private log(message: string, level: 'info' | 'warn' | 'error' = 'info') {
    const timestamp = new Date().toISOString();
    console.log(`[${timestamp}] ${level.toUpperCase()}: ${message}`);
  }

  // Vérification que le fichier de configuration existe
  private validateConfigFile(): boolean {
    if (!fs.existsSync(this.configFilePath)) {
      this.log(`Fichier de configuration non trouvé: ${this.configFilePath}`, 'error');
      return false;
    }

    this.log(`Fichier de configuration trouvé: ${this.configFilePath}`);
    return true;
  }

  // Lecture de la configuration actuelle
  private readCurrentConfig(): string | null {
    try {
      const content = fs.readFileSync(this.configFilePath, 'utf8');
      
      // Extraction des valeurs actuelles pour logging
      const urlMatch = content.match(/export const SUPABASE_URL = ["']([^"']+)["']/);
      const keyMatch = content.match(/export const SUPABASE_PUBLISHABLE_KEY = ["']([^"']+)["']/);
      
      if (urlMatch && keyMatch) {
        this.log(`Configuration actuelle - URL: ${urlMatch[1]}`);
        this.log(`Configuration actuelle - Clé: ${keyMatch[1].substring(0, 20)}...`);
      }
      
      return content;
    } catch (error) {
      this.log(`Erreur lecture configuration: ${error}`, 'error');
      return null;
    }
  }

  // Création d'une sauvegarde
  private createBackup(content: string): boolean {
    if (!this.options.createBackup) {
      return true;
    }

    try {
      // Création du répertoire de backup
      const backupDir = path.join(this.options.backupDir, 'config-backups');
      const migrationBackupDir = path.join(backupDir, `pre-migration-${this.timestamp}`);
      
      if (!fs.existsSync(migrationBackupDir)) {
        fs.mkdirSync(migrationBackupDir, { recursive: true });
      }

      // Sauvegarde du fichier
      const backupPath = path.join(migrationBackupDir, 'client.ts.backup');
      fs.writeFileSync(backupPath, content);
      
      // Création d'un fichier de métadonnées
      const metadataPath = path.join(migrationBackupDir, 'backup_metadata.json');
      const metadata = {
        timestamp: new Date().toISOString(),
        originalPath: this.configFilePath,
        backupReason: 'Pre-migration backup',
        targetUrl: this.options.target.url,
        targetDescription: this.options.target.description || 'Configuration update'
      };
      fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));

      this.log(`✅ Sauvegarde créée: ${backupPath}`);
      return true;
    } catch (error) {
      this.log(`Erreur création sauvegarde: ${error}`, 'error');
      return false;
    }
  }

  // Génération du nouveau contenu de configuration
  private generateNewConfig(): string {
    const { url, key, description } = this.options.target;
    
    return `
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.ts';

export const SUPABASE_URL = "${url}";
export const SUPABASE_PUBLISHABLE_KEY = "${key}";

// Configuration mise à jour le ${new Date().toISOString()}
// ${description || 'Migration configuration update'}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Initialize Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    debug: false, // Disable debug mode to reduce potential issues
  }
});

// Completely clear all auth data (for debugging) - not used in the app but can be used to clear the auth state if needed (e.g. if you want to test the auth flow)
export const cleanupAuthState = () => {
  try {
    // Clear all localStorage items related to Supabase auth
    Object.keys(localStorage).forEach(key => {
      if (key.includes('supabase') || key.includes('sb-')) {
        localStorage.removeItem(key);
      }
    });
    
    // Clear all sessionStorage items related to Supabase auth
    Object.keys(sessionStorage || {}).forEach(key => {
      if (key.includes('supabase') || key.includes('sb-')) {
        sessionStorage.removeItem(key);
      }
    });
    
    // Clear any cookies related to auth (optional but thorough)
    document.cookie.split(';').forEach(cookie => {
      const [name] = cookie.split('=');
      if (name.trim().includes('sb-')) {
        document.cookie = \`\${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;\`;
      }
    });
    
  } catch (error) {
    console.error('Error cleaning up auth state:', error);
  }
};
`;
  }

  // Écriture de la nouvelle configuration
  private writeNewConfig(newContent: string): boolean {
    try {
      fs.writeFileSync(this.configFilePath, newContent);
      this.log(`✅ Configuration mise à jour: ${this.configFilePath}`);
      return true;
    } catch (error) {
      this.log(`Erreur écriture configuration: ${error}`, 'error');
      return false;
    }
  }

  // Validation basique de la nouvelle configuration
  private validateNewConfig(): boolean {
    if (!this.options.validateConfig) {
      return true;
    }

    try {
      const content = fs.readFileSync(this.configFilePath, 'utf8');
      
      // Vérifications basiques
      if (!content.includes('SUPABASE_URL')) {
        this.log('SUPABASE_URL manquant dans la nouvelle configuration', 'error');
        return false;
      }
      
      if (!content.includes('SUPABASE_PUBLISHABLE_KEY')) {
        this.log('SUPABASE_PUBLISHABLE_KEY manquant dans la nouvelle configuration', 'error');
        return false;
      }
      
      if (!content.includes(this.options.target.url)) {
        this.log('URL cible non trouvée dans la configuration', 'error');
        return false;
      }
      
      if (!content.includes(this.options.target.key)) {
        this.log('Clé cible non trouvée dans la configuration', 'error');
        return false;
      }
      
      this.log('✅ Validation de la nouvelle configuration réussie');
      return true;
    } catch (error) {
      this.log(`Erreur validation configuration: ${error}`, 'error');
      return false;
    }
  }

  // Mise à jour d'autres fichiers si nécessaire
  private updateEnvironmentFiles(): boolean {
    try {
      // Mise à jour du .env.example si il existe
      const envExamplePath = path.join(process.cwd(), '.env.example');
      if (fs.existsSync(envExamplePath)) {
        let envContent = fs.readFileSync(envExamplePath, 'utf8');
        
        // Mise à jour des variables d'exemple
        envContent = envContent.replace(
          /VITE_SUPABASE_URL=.*/,
          `VITE_SUPABASE_URL=${this.options.target.url}`
        );
        
        // Note: on ne met pas la vraie clé dans .env.example
        envContent = envContent.replace(
          /VITE_SUPABASE_PUBLISHABLE_KEY=.*/,
          'VITE_SUPABASE_PUBLISHABLE_KEY=your_supabase_anon_key'
        );
        
        fs.writeFileSync(envExamplePath, envContent);
        this.log(`✅ .env.example mis à jour`);
      }
      
      return true;
    } catch (error) {
      this.log(`Erreur mise à jour fichiers environnement: ${error}`, 'warn');
      return true; // Non bloquant
    }
  }

  // Génération d'un rapport de mise à jour
  private generateUpdateReport(): void {
    const reportPath = path.join(this.options.backupDir, `config_update_${this.timestamp}.json`);
    
    const report = {
      timestamp: new Date().toISOString(),
      action: 'configuration_update',
      target: this.options.target,
      configFile: this.configFilePath,
      backupCreated: this.options.createBackup,
      validationPerformed: this.options.validateConfig,
      status: 'success'
    };
    
    try {
      if (!fs.existsSync(this.options.backupDir)) {
        fs.mkdirSync(this.options.backupDir, { recursive: true });
      }
      fs.writeFileSync(reportPath, JSON.stringify(report, null, 2));
      this.log(`📄 Rapport de mise à jour: ${reportPath}`);
    } catch (error) {
      this.log(`Erreur génération rapport: ${error}`, 'warn');
    }
  }

  // Exécution de la mise à jour complète
  async updateConfig(): Promise<boolean> {
    this.log('🚀 Démarrage de la mise à jour de configuration Supabase');
    this.log(`Nouvelle URL: ${this.options.target.url}`);
    this.log(`Description: ${this.options.target.description || 'Configuration update'}`);

    try {
      // Étape 1: Validation du fichier
      if (!this.validateConfigFile()) {
        return false;
      }

      // Étape 2: Lecture de la configuration actuelle
      const currentContent = this.readCurrentConfig();
      if (!currentContent) {
        return false;
      }

      // Étape 3: Création de la sauvegarde
      if (!this.createBackup(currentContent)) {
        return false;
      }

      // Étape 4: Génération et écriture de la nouvelle configuration
      const newContent = this.generateNewConfig();
      if (!this.writeNewConfig(newContent)) {
        return false;
      }

      // Étape 5: Validation de la nouvelle configuration
      if (!this.validateNewConfig()) {
        return false;
      }

      // Étape 6: Mise à jour des autres fichiers
      this.updateEnvironmentFiles();

      // Étape 7: Génération du rapport
      this.generateUpdateReport();

      this.log('🎉 Mise à jour de configuration terminée avec succès!');
      this.log('⚠️ N\'oubliez pas de rebuilder l\'application');
      
      return true;
    } catch (error) {
      this.log(`Erreur générale: ${error}`, 'error');
      return false;
    }
  }
}

// Fonction principale
async function main() {
  const args = process.argv.slice(2);
  
  // Affichage de l'aide
  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
Mise à jour Configuration Supabase

Usage: node update-config.ts [options]

Variables d'environnement:
  SUPABASE_TARGET_URL           URL de l'instance Supabase cible (requis)
  SUPABASE_TARGET_KEY           Clé API de l'instance cible (requis)
  SUPABASE_TARGET_DESCRIPTION   Description de la mise à jour (optionnel)
  BACKUP_DIR                    Répertoire des sauvegardes (défaut: ./migration-backups)
  SKIP_BACKUP                   Skip la création de sauvegarde (défaut: false)
  SKIP_VALIDATION               Skip la validation (défaut: false)

Exemples:
  # Migration vers auto-hébergé (utilise les variables .env)
  export SUPABASE_TARGET_URL="https://services-supabase.clubcreole.fr"
  export SUPABASE_TARGET_KEY="$SERVICE_SUPABASE_ANON_KEY"
  export SUPABASE_TARGET_DESCRIPTION="Migration vers instance auto-hébergée ClubCreole"
  node update-config.ts

  # Ou utilisation automatique des variables .env (recommandé)
  # Les variables SERVICE_SUPABASE_ANON_KEY sont automatiquement détectées
  node update-config.ts

  # Rollback vers cloud
  export SUPABASE_TARGET_URL="https://psryoyugyimibjhwhvlh.supabase.co"
  export SUPABASE_TARGET_KEY="$VITE_SUPABASE_PUBLISHABLE_KEY"
  export SUPABASE_TARGET_DESCRIPTION="Rollback vers Supabase cloud"
  node update-config.ts
`);
    process.exit(0);
  }

  // Lecture des variables d'environnement avec auto-détection
  let targetUrl = process.env.SUPABASE_TARGET_URL;
  let targetKey = process.env.SUPABASE_TARGET_KEY;
  
  // Auto-détection de la configuration cible depuis .env
  if (!targetUrl && process.env.SERVICE_SUPABASE_ANON_KEY) {
    targetUrl = 'https://services-supabase.clubcreole.fr';
    console.log('🔍 URL cible auto-détectée: https://services-supabase.clubcreole.fr');
  }
  
  if (!targetKey && process.env.SERVICE_SUPABASE_ANON_KEY) {
    targetKey = process.env.SERVICE_SUPABASE_ANON_KEY;
    console.log('🔍 Clé cible auto-détectée depuis SERVICE_SUPABASE_ANON_KEY');
  }

  const targetDescription = process.env.SUPABASE_TARGET_DESCRIPTION || 
                           'Migration vers instance Supabase auto-hébergée';
  const backupDir = process.env.BACKUP_DIR || './migration-backups';
  const skipBackup = process.env.SKIP_BACKUP === 'true';
  const skipValidation = process.env.SKIP_VALIDATION === 'true';

  // Validation des paramètres requis
  if (!targetUrl || !targetKey) {
    console.error('❌ Configuration cible requise');
    console.error('');
    console.error('Options:');
    console.error('  1. Variables explicites:');
    console.error('     export SUPABASE_TARGET_URL="https://your-instance.com"');
    console.error('     export SUPABASE_TARGET_KEY="your_api_key"');
    console.error('');
    console.error('  2. Auto-détection depuis .env:');
    console.error('     SERVICE_SUPABASE_ANON_KEY (détecté: ' + 
                  (process.env.SERVICE_SUPABASE_ANON_KEY ? 'Oui' : 'Non') + ')');
    console.error('');
    console.error('État actuel:');
    console.error('  Target URL: ' + (targetUrl || 'Non définie'));
    console.error('  Target Key: ' + (targetKey ? 'Présente' : 'Manquante'));
    process.exit(1);
  }

  // Configuration de la mise à jour
  const options: UpdateOptions = {
    target: {
      url: targetUrl,
      key: targetKey,
      description: targetDescription
    },
    createBackup: !skipBackup,
    backupDir,
    validateConfig: !skipValidation
  };

  // Exécution de la mise à jour
  const updater = new SupabaseConfigUpdater(options);
  const success = await updater.updateConfig();
  
  process.exit(success ? 0 : 1);
}

// Gestion des erreurs non capturées
process.on('unhandledRejection', (reason, promise) => {
  console.error('Erreur non gérée:', reason);
  process.exit(1);
});

// Exécution si script appelé directement
if (require.main === module) {
  main().catch(console.error);
}

export { SupabaseConfigUpdater, UpdateOptions, SupabaseConfig };