
-- Table pour les médiums/voyants
CREATE TABLE public.voyance_mediums (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  specialties text[] NOT NULL DEFAULT '{}',
  description text NOT NULL,
  image text NOT NULL,
  experience_years integer NOT NULL DEFAULT 0,
  rating numeric(2,1) NOT NULL DEFAULT 0.0 CHECK (rating >= 0 AND rating <= 5),
  price_per_session numeric(10,2) NOT NULL,
  availability_schedule jsonb NOT NULL DEFAULT '{}',
  contact_phone text,
  contact_email text,
  contact_whatsapp text,
  languages text[] NOT NULL DEFAULT '{français}',
  consultation_types text[] NOT NULL DEFAULT '{présentiel}',
  location text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Table pour les avis clients des médiums
CREATE TABLE public.voyance_reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medium_id integer NOT NULL REFERENCES public.voyance_mediums(id) ON DELETE CASCADE,
  client_name text NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text NOT NULL,
  consultation_date date NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Table pour les demandes de consultation
CREATE TABLE public.voyance_consultations (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  medium_id integer NOT NULL REFERENCES public.voyance_mediums(id) ON DELETE CASCADE,
  client_name text NOT NULL,
  client_email text NOT NULL,
  client_phone text NOT NULL,
  preferred_date date NOT NULL,
  preferred_time text NOT NULL,
  consultation_type text NOT NULL DEFAULT 'présentiel',
  message text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed')),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Insérer quelques médiums d'exemple
INSERT INTO public.voyance_mediums (name, specialties, description, image, experience_years, rating, price_per_session, contact_phone, contact_email, languages, consultation_types, location) VALUES
('Madame Solange', '{Tarot, Voyance pure, Médiumnité}', 'Médium depuis plus de 20 ans, spécialisée dans la voyance pure et la lecture de tarot. Je vous aide à éclaircir vos questionnements sur l''amour, le travail et la famille.', '/placeholder.svg', 20, 4.8, 60.00, '+590 690 12 34 56', 'solange.voyance@email.com', '{français, créole}', '{présentiel, téléphone, visio}', 'Pointe-à-Pitre'),
('Maître Antoine', '{Cartomancie, Numérologie, Astrologie}', 'Cartomancien et numérologue expérimenté. Consultation personnalisée pour vous guider dans vos choix de vie et révéler votre potentiel caché.', '/placeholder.svg', 15, 4.6, 50.00, '+590 690 65 43 21', 'antoine.cartes@email.com', '{français}', '{présentiel, téléphone}', 'Basse-Terre'),
('Mama Josephine', '{Spiritisme, Désenvoûtement, Protection}', 'Spécialiste en spiritisme et protection spirituelle. Plus de 25 ans d''expérience dans l''aide aux personnes en difficulté spirituelle.', '/placeholder.svg', 25, 4.9, 80.00, '+590 690 98 76 54', 'josephine.spirit@email.com', '{français, créole, anglais}', '{présentiel}', 'Le Gosier'),
('Voyant Marcus', '{Voyance par téléphone, Pendule, Cristallomancie}', 'Voyant spécialisé dans les consultations à distance. Utilise le pendule et les cristaux pour des prédictions précises.', '/placeholder.svg', 12, 4.4, 45.00, '+590 690 11 22 33', 'marcus.voyant@email.com', '{français, anglais}', '{téléphone, visio}', 'Saint-François');

-- Insérer quelques avis d'exemple
INSERT INTO public.voyance_reviews (medium_id, client_name, rating, comment, consultation_date) VALUES
(1, 'Marie L.', 5, 'Consultation exceptionnelle ! Madame Solange a su cerner mes préoccupations avec une précision remarquable.', '2024-01-15'),
(1, 'Jean-Paul D.', 4, 'Très bonne voyante, conseils utiles et bienveillants. Je recommande vivement.', '2024-02-03'),
(2, 'Claudette M.', 5, 'Maître Antoine m''a aidée à prendre des décisions importantes. Merci pour cette guidance précieuse.', '2024-01-28'),
(3, 'Robert K.', 5, 'Mama Josephine a résolu mes problèmes spirituels. Une vraie professionnelle !', '2024-02-10'),
(4, 'Sandra B.', 4, 'Consultation par téléphone très satisfaisante avec Marcus. Prédictions justes.', '2024-02-05');

-- Activer RLS sur les tables
ALTER TABLE public.voyance_mediums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voyance_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voyance_consultations ENABLE ROW LEVEL SECURITY;

-- Politiques RLS pour voyance_mediums (lecture publique, modification admin)
CREATE POLICY "Public can view active mediums" ON public.voyance_mediums
  FOR SELECT USING (is_active = true);

CREATE POLICY "Admins can manage mediums" ON public.voyance_mediums
  FOR ALL USING (is_admin());

-- Politiques RLS pour voyance_reviews (lecture publique)
CREATE POLICY "Public can view reviews" ON public.voyance_reviews
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage reviews" ON public.voyance_reviews
  FOR ALL USING (is_admin());

-- Politiques RLS pour voyance_consultations (utilisateurs peuvent créer, admins peuvent tout voir)
CREATE POLICY "Anyone can create consultations" ON public.voyance_consultations
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Admins can view all consultations" ON public.voyance_consultations
  FOR SELECT USING (is_admin());

CREATE POLICY "Admins can update consultations" ON public.voyance_consultations
  FOR UPDATE USING (is_admin());
