create table public.accommodations (
  id serial not null,
  name text not null,
  type text not null,
  location text not null,
  price numeric not null,
  rating numeric(2, 1) not null,
  image text not null,
  gallery_images jsonb not null,
  features jsonb not null,
  description text not null,
  rooms integer not null,
  bathrooms integer not null,
  max_guests integer not null,
  amenities jsonb not null,
  rules jsonb not null,
  discount integer null,
  constraint accommodations_pkey primary key (id)
) TABLESPACE pg_default;

create table public.activities (
  id bigint generated by default as identity not null,
  name text not null,
  path text not null,
  icon_name text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  is_active boolean not null default true,
  constraint activities_pkey primary key (id),
  constraint activities_name_unique unique (name)
) TABLESPACE pg_default;

create table public.activity_images (
  id serial not null,
  activity_id integer not null,
  url text not null,
  alt_text text not null,
  title text not null,
  sort_order integer null default 0,
  created_at timestamp with time zone null default now(),
  constraint activity_images_pkey primary key (id),
  constraint activity_images_activity_id_fkey foreign KEY (activity_id) references leisure_activities (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_activity_images_activity_id on public.activity_images using btree (activity_id) TABLESPACE pg_default;